// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfrxwvwlnamkbfaderjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mcnh3dndsbmFta2JmYWRlcmp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MjEzMDIsImV4cCI6MjA2MzA5NzMwMn0.yjL4obIEpVEyKtqcdc6TzmZYI6ve8n_P-QIFY2qyoNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);